name: Build distribution artifacts and deploy to GitHub Releases

on:
  - push
  - workflow_dispatch

env:
  AVR_TOOLCHAIN_TIMESTAMP: "202209132341"

permissions:
  contents: write

concurrency:
  group: dist
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y ninja-build
          wget -q "https://github.com/rafaelmartins/avr-toolchain/releases/download/avr-toolchain-linux-amd64-${AVR_TOOLCHAIN_TIMESTAMP}/avr-toolchain-linux-amd64-${AVR_TOOLCHAIN_TIMESTAMP}.tar.xz"{,.sha512}
          sha512sum -c "avr-toolchain-linux-amd64-${AVR_TOOLCHAIN_TIMESTAMP}.tar.xz.sha512"
          tar -xf "avr-toolchain-linux-amd64-${AVR_TOOLCHAIN_TIMESTAMP}.tar.xz"

      - name: Build source code
        run: |
          export PATH="$(pwd)/avr/bin:${PATH}"
          cmake -D CMAKE_BUILD_TYPE=Release -S "$(pwd)" -B "$(pwd)/build" -G Ninja
          cmake --build "$(pwd)/build" --target all

      - name: Upload HEX file
        uses: actions/upload-artifact@v3
        with:
          name: ihex
          path: build/*.hex

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download bdist
        uses: actions/download-artifact@v3
        with:
          name: ihex

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: "ghost-julialabs-${{ github.ref_name }}"
          artifacts: "*.hex"
          allowUpdates: true
          removeArtifacts: true
          generateReleaseNotes: true
